services:
  E2E:
    image: python:3.12.0-alpine3.18
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/automation
    command: /bin/sh -c "ls -ls && pytest --version && pytest -m login"
    working_dir: /automation