name: Framework Health Check Test
on: push
jobs:
  Health_check:
    runs-on: macos-latest
#    services:
#      selenium:
#        image: selenium/standalone-chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker
        run: |
          docker compose build
      - name: Run Docker
        run: |
          docker compose up