name: E2E Health-Check
on: push

jobs:
  e2e-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Docker Compose build
        run: |
          docker compose build
      - name: Docker compose build
        run: |
          docker compose up