name: Health Check
on: push
jobs:
  E2E:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docker
        run: |
          docker compose build
      - name: Run docker
        run: |
          docker compose up
          
