name: Framework Health Check Test
on: push
jobs:
  Health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker
        run: |
          docker compose build
      - name: Run Docker
        run: |
          docker compose up