name: E2E Testing
on:
  schedule:
    - cron: "5/02 * * * *"

jobs:
  e2e-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Build docker container
        run: |
          docker compose build
      - name: Run the container
        run: |
          docker compose up